apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: june-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: june-services
rules:
  - apiGroups: [""]
    resources: ["secrets","events"]
    verbs: ["get","list","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: june-services
subjects:
  - kind: ServiceAccount
    name: tailscale
    namespace: june-services
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
