apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: june-services
  labels:
    app.kubernetes.io/name: tailscale-auth
stringData:
  TS_AUTHKEY: "REPLACE_WITH_HEADSCALE_PREAUTH_KEY"
