apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: livekit-ingress
  namespace: media-stack
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/server-snippets: |
      client_body_buffer_size 10M;
      client_max_body_size 10M;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - livekit.ozzu.world
    secretName: ozzu-world-wildcard-tls
  rules:
  - host: livekit.ozzu.world
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: livekit-livekit-server
            port:
              number: 80
