apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: livekit-udp-route
  namespace: stunner
spec:
  parentRefs:
    - name: stunner-gateway
  rules:
    - backendRefs:
        - name: livekit-udp
          namespace: june-services
          port: 7882